[es]
# Elasticsearch configuration
# Elasticsearch address
address = ["http://127.0.0.1:8200"]

# Elasticsearch authentication
# Elasticsearch username
username = "superuser"

# Elasticsearch password
password = "1234"

# Elasticsearch connection pool
max_idle_conns = 100
max_idle_conns_perhost = 10

# Elasticsearch connection timeout
idle_conn_timeout = 90